import env from '#start/env'
import type { MeuchEntry } from '../types/meuch_map.js'
import { createClientValidator } from '#validators/client'
import { createSupplierValidator } from '#validators/supplier'
import { createOpportunityValidator } from '#validators/opportunity'
import { productValidator } from '#validators/product'
import { createOrderValidator } from '#validators/order'
import { createClientPaymentValidator } from '#validators/client_payments'
import { createPriceRequestValidator } from '#validators/price_request'
import { createPurchaseOrderValidator } from '#validators/purchase_order'
import { createSupplierPaymentValidator } from '#validators/supplier_payment'

export default class MeuchController {
  public async meuch(): Promise<MeuchEntry[]> {
    return [
      // Client
      {
        key: `${env.get('API_CODE')}_LIST_CLIENT`,
        endpoint: `/api/clients`,
        description: 'Récupère tout les clients',
        type: 'GET',
        routeFormat: null,
        queryParams: null,
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_CREATE_CLIENT`,
        endpoint: `/api/clients`,
        description: 'Crée un client',
        type: 'POST',
        routeFormat: null,
        queryParams: null,
        body: this.extractVineSchema(createClientValidator as any),
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          lastName: 'string',
          firstName: 'string',
          companyName: 'string',
          email: 'string',
          opportunities: 'array',
          quotes: 'array',
          orders: 'array',
        },
      },
      {
        key: `${env.get('API_CODE')}_SEARCH_CLIENT`,
        endpoint: `/api/clients/search`,
        description: 'Recherche un client',
        type: 'GET',
        routeFormat: null,
        queryParams: ['query'],
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_GET_CLIENT`,
        endpoint: `/api/clients`,
        description: 'Récupère un client',
        type: 'GET',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          lastName: 'string',
          firstName: 'string',
          companyName: 'string',
          email: 'string',
          opportunities: 'array',
          quotes: 'array',
          orders: 'array',
        },
      },
      {
        key: `${env.get('API_CODE')}_DELETE_CLIENT`,
        endpoint: `/api/clients`,
        description: 'Supprime un client',
        type: 'DELETE',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {},
      },

      // Suppliers
      {
        key: `${env.get('API_CODE')}_LIST_SUPPLIER`,
        endpoint: `/api/suppliers`,
        description: 'Récupère tout les fournisseurs',
        type: 'GET',
        routeFormat: null,
        queryParams: null,
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_CREATE_SUPPLIER`,
        endpoint: `/api/suppliers`,
        description: 'Crée un fournisseur',
        type: 'POST',
        routeFormat: null,
        queryParams: null,
        body: this.extractVineSchema(createSupplierValidator as any),
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          lastName: 'string',
          firstName: 'string',
          companyName: 'string',
          email: 'string',
          purchaseOrders: 'array',
          priceRequests: 'array',
          supplierPayments: 'array',
        },
      },
      {
        key: `${env.get('API_CODE')}_SEARCH_SUPPLIER`,
        endpoint: `/api/suppliers/search`,
        description: 'Recherche un fournisseur',
        type: 'GET',
        routeFormat: null,
        queryParams: ['query'],
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_GET_SUPPLIER`,
        endpoint: `/api/suppliers`,
        description: 'Récupère un fournisseur',
        type: 'GET',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          lastName: 'string',
          firstName: 'string',
          companyName: 'string',
          email: 'string',
          purchaseOrders: 'array',
          priceRequests: 'array',
          supplierPayments: 'array',
        },
      },
      {
        key: `${env.get('API_CODE')}_DELETE_SUPPLIER`,
        endpoint: `/api/suppliers`,
        description: 'Supprime un fournisseur',
        type: 'DELETE',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {},
      },

      // Opportunities
      {
        key: `${env.get('API_CODE')}_LIST_OPPORTUNITY`,
        endpoint: `/api/opportunities`,
        description: 'Récupère tout les opportunités',
        type: 'GET',
        routeFormat: null,
        queryParams: null,
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_CREATE_OPPORTUNITY`,
        endpoint: `/api/opportunities`,
        description: 'Crée une opportunité',
        type: 'POST',
        routeFormat: null,
        queryParams: null,
        body: this.extractVineSchema(createOpportunityValidator),
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          client: 'object',
          products: 'array',
          status: 'string',
          price: 'number',
        },
      },
      {
        key: `${env.get('API_CODE')}_SEARCH_OPPORTUNITY`,
        endpoint: `/api/opportunities/search`,
        description: 'Recherche une opportunité',
        type: 'GET',
        routeFormat: null,
        queryParams: ['query'],
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_GET_OPPORTUNITY`,
        endpoint: `/api/opportunities`,
        description: 'Récupère une opportunité',
        type: 'GET',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          client: 'object',
          products: 'array',
          status: 'string',
          price: 'number',
        },
      },
      {
        key: `${env.get('API_CODE')}_DELETE_OPPORTUNITY`,
        endpoint: `/api/opportunities`,
        description: 'Supprime une opportunité',
        type: 'DELETE',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {},
      },

      // Products
      {
        key: `${env.get('API_CODE')}_LIST_PRODUCT`,
        endpoint: `/api/products`,
        description: 'Récupère tout les produits',
        type: 'GET',
        routeFormat: null,
        queryParams: null,
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_CREATE_PRODUCT`,
        endpoint: `/api/products`,
        description: 'Crée un produit',
        type: 'POST',
        routeFormat: null,
        queryParams: null,
        body: this.extractVineSchema(productValidator),
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          name: 'string',
          description: 'string',
          price: 'number',
          type: 'string',
          products: 'array',
        },
      },
      {
        key: `${env.get('API_CODE')}_SEARCH_PRODUCT`,
        endpoint: `/api/products/search`,
        description: 'Recherche un produit',
        type: 'GET',
        routeFormat: null,
        queryParams: ['query'],
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_GET_PRODUCT`,
        endpoint: `/api/products`,
        description: 'Récupère un produit',
        type: 'GET',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          name: 'string',
          description: 'string',
          price: 'number',
          type: 'string',
          products: 'array',
        },
      },
      {
        key: `${env.get('API_CODE')}_DELETE_PRODUCT`,
        endpoint: `/api/products`,
        description: 'Supprime un produit',
        type: 'DELETE',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {},
      },

      // Orders
      {
        key: `${env.get('API_CODE')}_LIST_ORDER`,
        endpoint: `/api/orders`,
        description: 'Récupère tout les commandes',
        type: 'GET',
        routeFormat: null,
        queryParams: null,
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_CREATE_ORDER`,
        endpoint: `/api/orders`,
        description: 'Crée une commande',
        type: 'POST',
        routeFormat: null,
        queryParams: null,
        body: this.extractVineSchema(createOrderValidator),
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          client: 'object',
          products: 'array',
          status: 'string',
          price: 'number',
        },
      },
      {
        key: `${env.get('API_CODE')}_SEARCH_ORDER`,
        endpoint: `/api/orders/search`,
        description: 'Recherche une commande',
        type: 'GET',
        routeFormat: null,
        queryParams: ['query'],
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_GET_ORDER`,
        endpoint: `/api/orders`,
        description: 'Récupère une commande',
        type: 'GET',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          client: 'object',
          products: 'array',
          status: 'string',
          price: 'number',
        },
      },
      {
        key: `${env.get('API_CODE')}_DELETE_ORDER`,
        endpoint: `/api/orders`,
        description: 'Supprime une commande',
        type: 'DELETE',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {},
      },

      // Client payments
      {
        key: `${env.get('API_CODE')}_LIST_CLIENT_PAYMENT`,
        endpoint: `/api/client-payments`,
        description: 'Récupère tout les paiements client',
        type: 'GET',
        routeFormat: null,
        queryParams: null,
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_CREATE_CLIENT_PAYMENT`,
        endpoint: `/api/client-payments`,
        description: 'Crée un paiement client',
        type: 'POST',
        routeFormat: null,
        queryParams: null,
        body: this.extractVineSchema(createClientPaymentValidator),
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_GET_CLIENT_PAYMENT`,
        endpoint: `/api/client-payments`,
        description: 'Récupère un paiement client',
        type: 'GET',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_DELETE_CLIENT_PAYMENT`,
        endpoint: `/api/client-payments`,
        description: 'Supprime un paiement client',
        type: 'DELETE',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {},
      },

      // Price requests
      {
        key: `${env.get('API_CODE')}_LIST_PRICE_REQUEST`,
        endpoint: `/api/price-requests`,
        description: 'Récupère tout les demandes de prix',
        type: 'GET',
        routeFormat: null,
        queryParams: null,
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_CREATE_PRICE_REQUEST`,
        endpoint: `/api/price-requests`,
        description: 'Crée une demande de prix',
        type: 'POST',
        routeFormat: null,
        queryParams: null,
        body: this.extractVineSchema(createPriceRequestValidator),
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          client: 'object',
          products: 'array',
          status: 'string',
          price: 'number',
        },
      },
      {
        key: `${env.get('API_CODE')}_GET_PRICE_REQUEST`,
        endpoint: `/api/price-requests`,
        description: 'Récupère une demande de prix',
        type: 'GET',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          client: 'object',
          products: 'array',
          status: 'string',
          price: 'number',
        },
      },
      {
        key: `${env.get('API_CODE')}_DELETE_PRICE_REQUEST`,
        endpoint: `/api/price-requests`,
        description: 'Supprime une demande de prix',
        type: 'DELETE',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {},
      },

      // Purchase Orders
      {
        key: `${env.get('API_CODE')}_LIST_PURCHASE_ORDER`,
        endpoint: `/api/purchase-orders`,
        description: 'Récupère tout les commandes fournisseur',
        type: 'GET',
        routeFormat: null,
        queryParams: null,
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_CREATE_PURCHASE_ORDER`,
        endpoint: `/api/purchase-orders`,
        description: 'Crée une commande fournisseur',
        type: 'POST',
        routeFormat: null,
        queryParams: null,
        body: this.extractVineSchema(createPurchaseOrderValidator),
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          supplier: 'object',
          products: 'array',
          status: 'string',
          price: 'number',
        },
      },
      {
        key: `${env.get('API_CODE')}_GET_PURCHASE_ORDER`,
        endpoint: `/api/purchase-orders`,
        description: 'Récupère une commande fournisseur',
        type: 'GET',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          supplier: 'object',
          products: 'array',
          status: 'string',
          price: 'number',
        },
      },
      {
        key: `${env.get('API_CODE')}_DELETE_PURCHASE_ORDER`,
        endpoint: `/api/purchase-orders`,
        description: 'Supprime une commande fournisseur',
        type: 'DELETE',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {},
      },

      // Supplier payments
      {
        key: `${env.get('API_CODE')}_LIST_SUPPLIER_PAYMENT`,
        endpoint: `/api/supplier-payments`,
        description: 'Récupère tout les paiements fournisseur',
        type: 'GET',
        routeFormat: null,
        queryParams: null,
        body: null,
        response: {},
      },
      {
        key: `${env.get('API_CODE')}_CREATE_SUPPLIER_PAYMENT`,
        endpoint: `/api/supplier-payments`,
        description: 'Crée un paiement fournisseur',
        type: 'POST',
        routeFormat: null,
        queryParams: null,
        body: this.extractVineSchema(createSupplierPaymentValidator),
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          supplier: 'object',
          products: 'array',
          status: 'string',
          price: 'number',
        },
      },
      {
        key: `${env.get('API_CODE')}_GET_SUPPLIER_PAYMENT`,
        endpoint: `/api/supplier-payments`,
        description: 'Récupère un paiement fournisseur',
        type: 'GET',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {
          id: 'number',
          createdAt: 'string',
          updatedAt: 'string',
          supplier: 'object',
          products: 'array',
          status: 'string',
          price: 'number',
        },
      },
      {
        key: `${env.get('API_CODE')}_DELETE_SUPPLIER_PAYMENT`,
        endpoint: `/api/supplier-payments`,
        description: 'Supprime un paiement fournisseur',
        type: 'DELETE',
        routeFormat: '/id',
        queryParams: null,
        body: null,
        response: {},
      },
    ]
  }

  private extractVineSchema(validator: any): Record<string, string> {
    const properties = validator.toJSON().schema.schema.properties

    const result: Record<string, string> = {}

    properties.forEach((property: any) => {
      result[property.fieldName] = property.subtype
    })

    return result
  }
}
